#pragma once
#include <iostream>
#include <string>
#include <vector>
#include "Token.h"

typedef enum { STOP_CODE, POP_TOP, ROT_TWO, ROT_THREE, DUP_TOP, ROT_FOUR, NOP, UNARY_POSITIVE, UNARY_NEGATIVE, UNARY_NOT, UNARY_CONVERT, UNARY_INVERT, LIST_APPEND, BINARY_POWER, BINARY_MULTIPLY, BINARY_DIVIDE, BINARY_MODULO, BINARY_ADD, BINARY_SUBTRACT, BINARY_SUBSCR, BINARY_FLOOR_DIVIDE, BINARY_TRUE_DIVIDE, INPLACE_FLOOR_DIVIDE, INPLACE_TRUE_DIVIDE, SLICE, SLICE1, SLICE2, SLICE3, STORE_SLICE, STORE_SLICE1, STORE_SLICE2, STORE_SLICE3, DELETE_SLICE, DELETE_SLICE1, DELETE_SLICE2, DELETE_SLICE3, INPLACE_ADD, INPLACE_SUBTRACT, INPLACE_MULTIPLY, INPLACE_DIVIDE, INPLACE_MODULO, STORE_SUBSCR, DELETE_SUBSCR, BINARY_LSHIFT, BINARY_RSHIFT, BINARY_AND, BINARY_XOR, BINARY_OR, INPLACE_POWER, GET_ITER, PRINT_EXPR, PRINT_ITEM, PRINT_NEWLINE, PRINT_ITEM_TO, PRINT_NEWLINE_TO, INPLACE_LSHIFT, INPLACE_RSHIFT, INPLACE_AND, INPLACE_XOR, INPLACE_OR, BREAK_LOOP, WITH_CLEANUP, LOAD_LOCALS, RETURN_VALUE, IMPORT_STAR, EXEC_STMT, YIELD_VALUE, POP_BLOCK, END_FINALLY, BUILD_CLASS, STORE_NAME, DELETE_NAME, UNPACK_SEQUENCE, FOR_ITER, STORE_ATTR, DELETE_ATTR, STORE_GLOBAL, DELETE_GLOBAL, DUP_TOPX, LOAD_CONST, LOAD_NAME, BUILD_TUPLE, BUILD_LIST, BUILD_MAP, LOAD_ATTR, COMPARE_OP, IMPORT_NAME, IMPORT_FROM, JUMP_FORWARD, JUMP_IF_FALSE, JUMP_IF_TRUE, JUMP_ABSOLUTE, LOAD_GLOBAL, CONTINUE_LOOP, SETUP_LOOP, SETUP_EXCEPT, SETUP_FINALLY, LOAD_FAST, STORE_FAST, DELETE_FAST, RAISE_VARARGS, CALL_FUNCTION, MAKE_FUNCTION, BUILD_SLICE, MAKE_CLOSURE, LOAD_CLOSURE, LOAD_DEREF, STORE_DEREF, CALL_FUNCTION_VAR, CALL_FUNCTION_KW, CALL_FUNCTION_VAR_KW, EXTENDED_ARG} OpCodeCommands;

class ByteCode
{
public:
	OpCodeCommands OpCode;
	int OperandArg;

	ByteCode(OpCodeCommands opCode, int operandArg);
	ByteCode(OpCodeCommands opCode);
};